### ISSUE TITLE
响应状态码错误无法使用

### ISSUE THREAD

**Issue by Surgey516** [Ayin-cc/RobClasses-Tool-for-SCU#1]
一运行就闪退，错误代码截图如下
![image](https://github.com/Ayin-cc/RobClasses-Tool-for-SCU/assets/65482713/bf220c1f-d065-4b15-bc3d-4862d458d287)

**Comment by Surgey516** [comment]
有没有什么办法解决

**Comment by Ayin-cc** [comment]
这是因为ChromeDriver版本不匹配，请前往https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json 下载相应版本(120.0.6099)。

**Comment by lansheepsheepbigking** [comment]
伟大的学长/学姐，程序运行前半段很正常。但输入验证码时，我输对了，也登进去了，但还会弹出新的登录页面，后退一步也显示正常。请问怎么解决啊，明天要抢课了。呜呜呜呜呜呜呜呜呜。再次表示感谢。

**Comment by lansheepsheepbigking** [comment]
![07969507-3ed9-4383-a1ec-f6e9cba57d2a](https://github.com/user-attachments/assets/1086d2e6-ef8d-4fda-b11d-71fbb6ce46cc)
这是我的代码运行截图。请帮我看看问题出现在哪里。谢谢！
